/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-23T13:29:56.597Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "3366d8cc-8032-4fb2-8b23-30dc3577fd10",
    name: "Lens Reviews",
    slug: "lens-reviews",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "c9fa8d3f-0869-4094-9034-d8886616ecba",
        name: "Randolph Engineering",
        slug: "randolph-engineering",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "9ac09f7b-a914-4f1c-b24d-b7a18f011155",
        name: "Oakley",
        slug: "oakley",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "eca83deb-2397-4b4b-8f3a-98838b490fe1",
        name: "Maui Jim",
        slug: "maui-jim",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "bb00a42f-4433-4035-ac89-cf652f362dac",
        name: "Costa Del Mar",
        slug: "costa-del-mar",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "2175f545-4ae2-4c7e-b70e-7a1cc9400e20",
        name: "Island Optics",
        slug: "island-optics",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4bdfc2a1-8e76-454a-82d5-98fca9742b64",
        name: "Persol",
        slug: "persol",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "2e69c8e1-309a-4ec7-a1f8-99b8c5f8388e",
    name: "Lens Technology Guides",
    slug: "lens-technology-guides",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "35a86c1f-ac3c-4ca3-b608-9f5ed83ab8d1",
        name: "Polarized vs Non-Polarized",
        slug: "polarized-vs-non-polarized",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "7c971c44-8a90-4c1f-9934-c3205c03daa4",
        name: "Lens Colors",
        slug: "lens-colors",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "a8072781-3b49-469b-ba56-af8c84182333",
        name: "Lens Coatings",
        slug: "lens-coatings",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "df5a1298-8a21-4030-b1da-9ce0ed64b702",
        name: "Mirror Effects",
        slug: "mirror-effects",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "a4fc7789-c304-4762-a0eb-abb03c42a781",
    name: "Buying Guides",
    slug: "buying-guides",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "c5783cd7-6050-4f94-b6e1-e10ff60c85c8",
        name: "Best Fall Lenses",
        slug: "best-fall-lenses",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "e21ecb04-945e-49ce-b446-d4ba20d91390",
        name: "Prescription Options",
        slug: "prescription-options",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "092d2e0d-ef64-499b-ac3f-fd601ea7b2f0",
        name: "Online Purchasing Tips",
        slug: "online-purchasing-tips",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "7819c3e9-11a3-49a8-af9e-255da4e59bf4",
    name: "Care & Maintenance",
    slug: "care--maintenance",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "0ccd7a69-bb8b-4b65-bc0a-320868086e82",
        name: "Fog Prevention",
        slug: "fog-prevention",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "d15640c2-ef8f-40ac-bab6-e80a3a8a4e80",
        name: "Cleaning Tips",
        slug: "cleaning-tips",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "515b7b15-1d19-4d1d-9c5b-5089095bf92f",
        name: "Storage Solutions",
        slug: "storage-solutions",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
