/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Lens Insight
 * Generated: 2025-12-23T13:29:56.597Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "f43c99b7-1536-49d5-a8a2-6a3ec5d1b789",
    name: "Lens Insight",
    description: "Lens Insight offers expert reviews and educational content on eyewear technology, focusing on performance and innovation for discerning consumers.",
    url: "https://lens-insight-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Unveiling the future of eyewear with expert insights and reviews"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Lens Insight",
    subtitle: "Unveiling the future of eyewear with expert insights and reviews"
  },

  // Default author information
  author: {
    name: "Lens Insight Team",
    bio: "Lens Insight offers expert reviews and educational content on eyewear technology, focusing on performance and innovation for discerning consumers.",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Eyewear Technology and Reviews Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Lens Insight delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Randolph Engineering",
      icon: "FileText",
      slug: "randolph-engineering"
    },
    { 
      name: "Fog Prevention",
      icon: "FileText",
      slug: "fog-prevention"
    },
    { 
      name: "Best Fall Lenses",
      icon: "FileText",
      slug: "best-fall-lenses"
    },
    { 
      name: "Polarized vs Non-Polarized",
      icon: "FileText",
      slug: "polarized-vs-non-polarized"
    },
    { 
      name: "Lens Reviews",
      icon: "FileText",
      slug: "lens-reviews"
    },
    { 
      name: "Lens Colors",
      icon: "FileText",
      slug: "lens-colors"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "c9caa371-2921-4959-ac17-b27d7a6edf75",
      name: "Ethan Parker",
      bio: "Ethan Parker writes with an adventurous spirit and a keen eye for detail, drawing from his experiences in diverse outdoor settings to provide authentic and practical reviews. His engaging and straightforward style resonates with active readers looking for honest feedback and real-world performance of sunglasses in various environments.",
      image: "/authors/c9caa371-2921-4959-ac17-b27d7a6edf75.jpg",
      role: "Outdoor Enthusiast and Gear Reviewer"
    },
    {
      id: "6380bbe3-47b4-4a65-a8df-2d36797b8541",
      name: "Lily Martinez",
      bio: "Lily Martinez combines her flair for fashion with a deep knowledge of eyewear trends, offering a sophisticated and stylish perspective on sunglasses. Her writing is vibrant and trend-focused, appealing to fashion-forward readers who appreciate a blend of aesthetics and functionality in their eyewear choices.",
      image: "/authors/6380bbe3-47b4-4a65-a8df-2d36797b8541.jpg",
      role: "Fashion and Lifestyle Journalist"
    },
    {
      id: "d6f47a7d-1132-4aec-adf1-566b4d28a950",
      name: "Dr. Sophia Chen",
      bio: "Dr. Sophia Chen brings a meticulous and analytical approach to her writing, blending her deep expertise in optical sciences with a passion for cutting-edge technology. Her articles are rich with data-driven insights and technical details, making complex concepts accessible and engaging for readers who crave in-depth understanding.",
      image: "/authors/d6f47a7d-1132-4aec-adf1-566b4d28a950.jpg",
      role: "Optical Scientist and Sunglass Technology Specialist"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
